service-type = "CN"
data-dir = "./mo-data"

[log]
level = "fatal"

[cn]
uuid = "dd1dccb4-4d3c-41f8-b482-5251dc7a41bf"
port-base = 18000

[[fileservice]]
name = "LOCAL"
backend = "DISK"

[[fileservice]]
name = "SHARED"
backend = "DISK"
data-dir = "mo-data/shared"

[fileservice.cache]
memory-capacity = "8GB"
disk-capacity = "8GB"
disk-path = "mo-data/file-service-cache"

[[fileservice]]
name = "ETL"
backend = "DISK-ETL"


